// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Countdown: typeof import('./src/components/main-view/Countdown.vue')['default']
    DarkButton: typeof import('./src/layouts/components/shortcurs-button/DarkButton.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HourMeter: typeof import('./src/components/main-view/HourMeter.vue')['default']
    LanguageButton: typeof import('./src/layouts/components/shortcurs-button/LanguageButton.vue')['default']
    MainEditButton: typeof import('./src/layouts/components/shortcurs-button/MainEditButton.vue')['default']
    MainLayoutBox: typeof import('./src/components/main-view/MainLayoutBox.vue')['default']
    MyFooter: typeof import('./src/layouts/components/MyFooter.vue')['default']
    MyHeader: typeof import('./src/layouts/components/MyHeader.vue')['default']
    MyMain: typeof import('./src/layouts/components/MyMain.vue')['default']
    MyMenu: typeof import('./src/layouts/components/MyMenu.vue')['default']
    MyShortcuts: typeof import('./src/layouts/components/MyShortcuts.vue')['default']
    MySystemMenu: typeof import('./src/layouts/components/MySystemMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
